# Inserts a blank line between shell prompts
format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$conda\
$fill\
$env_var$hostname$os\
\n\r$character"""

add_newline = false
[fill]
symbol = ' '

[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'


# ~/.config/starship.toml
[env_var]
format="[$env_value](purple bold)"
variable = 'USER'
# ~/.config/starship.toml

[os]
disabled=false
format="[$symbol](bold white)"
[os.symbols]
Macos=" 🍺 "
# 


[hostname]
ssh_only=true
ssh_symbol=" ☁️"
format='[$ssh_symbol ($hostname)](red bold)'


[conda]
ignore_base=false
symbol=" "
format="[$symbol$environment]($style)"
